version: '3.5'

services:
  php:
    container_name: chat_api_php
    image: fgamess/php7-stack-symfony
    environment:
      - KERNEL_CLASS=App\Kernel
    volumes:
      - .:/var/www:cached
      - ./logs:/var/logs:cached
    ports:
      - 8002:8000
    networks:
      - app_network
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: chat_api_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: chat_api_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chat_api_phpmyadmin
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8010:80
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
volumes:
    logs:
