<?php

namespace AppBundle\Repository;

/**
 * ContactRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
