<?php

namespace App\Repository;
use App\Entity\ContactRequest;
use Doctrine\ORM\EntityManagerInterface;

/**
 * ContactRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRequestRepository
{
    /** @var EntityManagerInterface $em */
    private $em;

    /**
     * ContactRequestRepository constructor.
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->em = $entityManager;
    }

    public function save($entity)
    {
        $this->em->persist($entity);
        $this->em->flush();
    }

    public function find(int $id)
    {
        return $this->em->find(ContactRequest::class, $id);
    }
}
