version: '2'

services:
  php:
    container_name: chat_api_php
    build: php7
    volumes:
      - ..:/var/www
      - chat-api-unison-sync:/var/www:nocopy
    ports:
      - 9000:80
  nginx:
    container_name: chat_api_nginx
    build: nginx
    ports:
      - 8000:80
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ../logs/nginx/:/var/log/nginx
  db:
    image: mariadb:latest
    container_name: chat_api_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: chat_api_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
volumes:
  chat-api-unison-sync:
    external: true
